spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mustache:
    servlet:
      expose-request-attributes: true

server:
  servlet:
    session:
      timeout: 90m